#!/usr/bin/env bash
#
# create-draft-pr.sh — Deliver a draft-pr run as a reviewable draft PR
#
# Usage: ./harness/create-draft-pr.sh <run-dir> [--confirm-push] [--confirm-pr] [--force] [--dry-run]
#
# Phase 8 delivery script. Turns a completed `draft-pr` run into a GitHub
# draft PR — the first point where the lab writes to GitHub. Nothing is
# pushed or opened without explicit confirmation flags:
#
#   (no flags)       Stage + commit a local branch, print a preview, stop.
#   --confirm-push   Also push the branch to origin.
#   --confirm-pr     Also open a draft PR (implies --confirm-push).
#
# Branch/commit is delegated to create-local-branch.sh. The PR body is
# generated from the run report, with @mentions neutralized so no other
# users or bots are pinged. No reviewers, labels, or assignees are set.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"
source "${SCRIPT_DIR}/lib/agent.sh"

# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------
usage() {
  echo "Usage: $(basename "$0") <run-dir> [--confirm-push] [--confirm-pr] [--force] [--dry-run]"
  echo ""
  echo "Deliver a draft-pr run as a GitHub draft PR (confirmation-gated)."
  echo ""
  echo "By default this stages a local branch and prints a preview only."
  echo "Pushing and PR creation each require an explicit confirmation flag."
  echo ""
  echo "Options:"
  echo "  --confirm-push   Push the branch to origin"
  echo "  --confirm-pr     Open a draft PR (implies --confirm-push)"
  echo "  --force          Overwrite an existing local branch of the same name"
  echo "  --dry-run        Print every intended git/gh command; make no changes"
  exit 1
}

# ---------------------------------------------------------------------------
# Mode check — Phase 8 spec: draft PRs only come from draft-pr runs
# ---------------------------------------------------------------------------
REQUIRED_MODE="draft-pr"

# ---------------------------------------------------------------------------
# Neutralize @mentions so no users/bots are pinged in the PR body.
# Mirrors scripts/macos/pr-bot-worker.sh: backtick-wrap the @ and insert a
# zero-width space (U+200B) before the username.
# ---------------------------------------------------------------------------
neutralize_mentions() {
  local zwsp
  zwsp="$(printf '\xe2\x80\x8b')"
  sed "s/@\([a-zA-Z0-9_-]\)/\`@\`${zwsp}\1/g"
}

# ---------------------------------------------------------------------------
# Arg parsing
# ---------------------------------------------------------------------------
if [[ $# -lt 1 ]]; then
  usage
fi

RUN_DIR="$1"
shift

CONFIRM_PUSH=false
CONFIRM_PR=false
FORCE=false
DRY_RUN=false
for arg in "$@"; do
  case "$arg" in
    --confirm-push) CONFIRM_PUSH=true ;;
    --confirm-pr)   CONFIRM_PR=true ;;
    --force)        FORCE=true ;;
    --dry-run)      DRY_RUN=true ;;
    -h|--help)      usage ;;
    *) die "Unknown argument: ${arg}" ;;
  esac
done

# --confirm-pr implies a push (the branch must exist on origin first)
if $CONFIRM_PR; then
  CONFIRM_PUSH=true
fi

# ---------------------------------------------------------------------------
# Validate run directory
# ---------------------------------------------------------------------------
if [[ ! -d "$RUN_DIR" ]]; then
  die "Run directory not found: ${RUN_DIR}"
fi

if [[ ! -f "${RUN_DIR}/run-metadata.json" ]]; then
  die "Not a valid run directory (missing run-metadata.json): ${RUN_DIR}"
fi

require_command jq

META="${RUN_DIR}/run-metadata.json"
run_id=$(jq -r '.run_id' "$META")
task_id=$(jq -r '.task_id' "$META")
title=$(jq -r '.title' "$META")
mode=$(jq -r '.mode' "$META")
repo_url=$(jq -r '.repo_url // empty' "$META")
base_ref=$(jq -r '.base_ref // empty' "$META")
[[ -z "$base_ref" ]] && base_ref="main"

if [[ "$mode" != "$REQUIRED_MODE" ]]; then
  die "Mode '${mode}' does not support draft PR delivery. Required mode: ${REQUIRED_MODE}"
fi

print_banner "Create Draft PR: ${run_id}"

worktree_path=$(resolve_worktree "$RUN_DIR")
branch_name="agent-lab/${task_id}"

# ---------------------------------------------------------------------------
# Build the PR body from the run report (fallback: metadata + changed files)
# ---------------------------------------------------------------------------
build_pr_body() {
  local report=""
  if [[ -f "${RUN_DIR}/summary.md" && -s "${RUN_DIR}/summary.md" ]]; then
    report="${RUN_DIR}/summary.md"
  elif [[ -f "${TSD_REPORTS_DIR}/${run_id}-report.md" && -s "${TSD_REPORTS_DIR}/${run_id}-report.md" ]]; then
    report="${TSD_REPORTS_DIR}/${run_id}-report.md"
  fi

  echo "> Draft PR generated by TSD Agent Lab (\`create-draft-pr.sh\`) from run \`${run_id}\`."
  echo "> Human review required before merge. Generated by an automated agent."
  echo ""

  if [[ -n "$report" ]]; then
    cat "$report"
  else
    # Fallback: assemble a minimal body from metadata + changed files
    echo "## Summary"
    echo ""
    echo "| Field | Value |"
    echo "|-------|-------|"
    echo "| Run ID | \`${run_id}\` |"
    echo "| Task ID | \`${task_id}\` |"
    echo "| Title | ${title} |"
    echo "| Mode | \`${mode}\` |"
    echo ""
    echo "## Changed files"
    echo ""
    if [[ -f "${RUN_DIR}/changed-files.txt" && -s "${RUN_DIR}/changed-files.txt" ]]; then
      echo '```'
      cat "${RUN_DIR}/changed-files.txt"
      echo '```'
    else
      echo "_No changed-files.txt recorded._"
    fi
  fi
}

pr_title="$title"
pr_body="$(build_pr_body | neutralize_mentions)"

# ---------------------------------------------------------------------------
# Preview — always printed first, before any push or PR creation
# ---------------------------------------------------------------------------
log_step "Preview"
log_info "Repo URL:  ${repo_url:-<from worktree remote>}"
log_info "Branch:    ${branch_name}"
log_info "Base:      ${base_ref}"
log_info "Title:     ${pr_title}"
log_info "Worktree:  ${worktree_path}"
echo ""
log_step "PR body:"
echo "----------------------------------------------------------------------"
echo "$pr_body"
echo "----------------------------------------------------------------------"
echo ""

# ---------------------------------------------------------------------------
# Dry-run — print every intended command, make no changes
# ---------------------------------------------------------------------------
if $DRY_RUN; then
  local_branch_cmd="${SCRIPT_DIR}/create-local-branch.sh ${RUN_DIR}"
  $FORCE && local_branch_cmd="${local_branch_cmd} --force"
  log_info "[dry-run] Would stage + branch + commit:"
  log_info "  ${local_branch_cmd}"
  if $CONFIRM_PUSH; then
    log_info "[dry-run] Would push branch:"
    log_info "  git -C ${worktree_path} push -u origin ${branch_name}"
  else
    log_info "[dry-run] Would stop after local branch (no --confirm-push)."
    log_info "  Manual push: git -C ${worktree_path} push -u origin ${branch_name}"
  fi
  if $CONFIRM_PR; then
    log_info "[dry-run] Would verify GitHub auth:"
    log_info "  gh auth status"
    log_info "[dry-run] Would open draft PR:"
    log_info "  (cd ${worktree_path} && gh pr create --draft --base ${base_ref} --head ${branch_name} \\"
    log_info "     --title '${pr_title}' --body-file ${RUN_DIR}/draft-pr-body.md)"
    log_info "  (no --reviewer, no --label, no --assignee)"
  fi
  exit 0
fi

# ---------------------------------------------------------------------------
# Stage + branch + commit (delegated to create-local-branch.sh)
# ---------------------------------------------------------------------------
log_step "Creating local branch (via create-local-branch.sh)..."
branch_args=()
$FORCE && branch_args+=(--force)
"${SCRIPT_DIR}/create-local-branch.sh" "$RUN_DIR" "${branch_args[@]+"${branch_args[@]}"}"

if ! git -C "$worktree_path" rev-parse --verify "refs/heads/${branch_name}" &>/dev/null; then
  die "Branch '${branch_name}' was not created (no changes to deliver?). Nothing pushed."
fi

# ---------------------------------------------------------------------------
# Gate: push
# ---------------------------------------------------------------------------
if ! $CONFIRM_PUSH; then
  echo ""
  log_success "Local branch ready: ${branch_name}"
  log_warn "Stopping before push (no --confirm-push)."
  log_step "To push this branch:"
  log_info "  git -C ${worktree_path} push -u origin ${branch_name}"
  log_step "To push and open a draft PR:"
  log_info "  $(basename "$0") ${RUN_DIR} --confirm-pr"
  exit 0
fi

log_step "Pushing branch to origin: ${branch_name}"
git -C "$worktree_path" push -u origin "$branch_name"
log_success "Branch pushed: ${branch_name}"

# ---------------------------------------------------------------------------
# Gate: draft PR
# ---------------------------------------------------------------------------
if ! $CONFIRM_PR; then
  echo ""
  log_success "Branch pushed. Stopping before PR creation (no --confirm-pr)."
  log_step "To open a draft PR:"
  log_info "  (cd ${worktree_path} && gh pr create --draft --base ${base_ref} --head ${branch_name})"
  exit 0
fi

require_command gh

log_step "Checking GitHub authentication..."
if ! gh auth status &>/dev/null; then
  die "GitHub CLI is not authenticated. Run 'gh auth status' for details, authenticate, and retry. No PR was created."
fi

body_file="${RUN_DIR}/draft-pr-body.md"
printf '%s\n' "$pr_body" > "$body_file"

log_step "Opening draft PR..."
pr_url=$(cd "$worktree_path" && gh pr create \
  --draft \
  --base "$base_ref" \
  --head "$branch_name" \
  --title "$pr_title" \
  --body-file "$body_file")

log_success "Draft PR created: ${pr_url}"
log_info "Branch:    ${branch_name}"
log_info "Base:      ${base_ref}"
log_info "PR body:   ${body_file}"
log_warn "This is a DRAFT PR. A human must review and mark it ready before merge."
